{% set name = "pyfive" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyfive-{{ version }}.tar.gz
  sha256: 8401ae6b2a86cfc7ad454c838bef5587271e0998dca9e5158fe84b194bf2095d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip !=21.3
    - setuptools >=80
    - setuptools_scm >=8
  run:
    - python >={{ python_min }}
    - numpy >=2

test:
  source_files:
    - tests
  requires:
    - python {{ python_min }}
    - pip
    - dask
    - flask
    - flask-cors
    - h5netcdf
    - h5py
    - moto
    - netcdf4
    - pytest
    - pytest-cov
    - pytest-html
    - pytest-xdist
    - python-lzf
    - s3fs
  commands:
    - pip check
    - pytest --ignore=tests/test_filter_pipeline_v2.py::test_hdf5_filters
    - p5dump -h
  imports:
    - pyfive

about:
  home: https://github.com/NCAS-CMS/pyfive
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'A pure Python HDF5 file reader'

extra:
  recipe-maintainers:
    - davidhassell
    - valeriupredoi
    - jjhelmus
