{% set name = "pyfive" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyfive-{{ version }}.tar.gz
  sha256: 3851e99784e54ab4f30e19d6c59faa88535c40f714233a6e5f30a3fcd38aa511

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip !=21.3
    - setuptools >=40.6.0
    - setuptools_scm >=6.2
  run:
    - python >={{ python_min }}
    - numpy

test:
  source_files:
    - tests
  requires:
    - python {{ python_min }}
    - pip
    - dask
    - flask
    - flask-cors
    - h5netcdf
    - h5py
    - moto
    - netcdf4
    - pytest
    - pytest-cov
    - pytest-html
    - pytest-xdist
    - python-lzf
    - s3fs
  commands:
    - pip check
    - pytest
    - p5dump -h
  imports:
    - pyfive

about:
  home: https://github.com/NCAS-CMS/pyfive
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'A pure Python HDF5 file reader'

extra:
  recipe-maintainers:
    - davidhassell
    - valeriupredoi
    - jjhelmus
